# Generated by Django 3.1.1 on 2022-06-21 06:36

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('shorttext', models.TextField(blank=True, default=None, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(related_name='tags', to='myblog.PostTag')),
            ],
        ),
    ]
